### PR TITLE
make it work with Go 1.13

### LINKED ISSUE #10: It doesn't compile with go 1.13
Get a fresh build env en try running `make` when using go 1.13. (building on Mac)

1) `staticcheck` must be upgraded to 2019.2.3 to deal with v1.13
2) new version is tar.gz, so some logic in Makefile needs bending (like Promu)
3) fails with `make: *** [common-unused] Error 1`

### PR DESCRIPTION
**Pull request by hans-d**
fixes #10 

- update with latest Makefile.common
- fix reported lint issues
- commit dep changes

### CODE REVIEW

File: ssl_exporter.go [hunk 1]
```diff
@@ -375,12 +375,13 @@ func main() {
 	log.Infoln("Starting "+namespace+"_exporter", version.Info())
 	log.Infoln("Build context", version.BuildContext())
 
+	//lint:ignore SA1019 because
 	http.Handle(*metricsPath, prometheus.Handler())
```
Comment (ribbybibby) [inline ssl_exporter.go]: Rather than ignoring the check, could we not just switch to `promhttp.Handler()` as suggested?

Comment (hans-d) [reply ssl_exporter.go]: this ignore is only been moved from https://github.com/ribbybibby/ssl_exporter/blob/606f4f6032356292fea9b0f09c787a5be00511de/Makefile#L18 (different linter). didn't dive into doing the actual switch

Comment (ribbybibby) [reply ssl_exporter.go]: Aha, okay. I see. I can look at that separately.
